uint8 eeprom_script = 0
uint8 RGB = 1
uint8 white_flash = 2
uint8 red_flash = 3
uint8 green_flash = 4
uint8 blue_flash = 5
uint8 cyan_flash = 6
uint8 magenta_flash = 7
uint8 yellow_flash = 8
uint8 black = 9
uint8 hue_cycle = 10
uint8 moon_light = 11
uint8 virtual_candle = 12
uint8 water_reflections = 13
uint8 old_neon = 14
uint8 the_seasons = 15
uint8 thunderstorm = 16
uint8 stop_light = 17
uint8 morse_code = 18

uint8 id
int8 repetitions
int8 speed
